import {
  COLLABORATION_TOOL_CHECKPOINT_ACK_PATH,
  COLLABORATION_TOOL_CHECKPOINT_PREPARE_PATH
} from '../../shared/collaboration-tool-checkpoint-contract'
import type { PiAgentKind } from '../../shared/pi-agent-kind'

export function getPiCollaborationToolCheckpointModuleSourceLines(kind: PiAgentKind): string[] {
  if (kind !== 'pi') {
    return []
  }
  return [
    'const COLLABORATION_TOOL_CHECKPOINT_TIMEOUT_MS = 500',
    'let collaborationToolCheckpointPrepareInFlight = false',
    'let pendingCollaborationCheckpointAcks: { deliveryId: string; deliveryAttempt: number }[] = []',
    'let armedCollaborationCheckpointAcks: { deliveryId: string; deliveryAttempt: number }[] = []',
    '',
    'async function callCollaborationToolCheckpoint(path: string, payload: Record<string, unknown>): Promise<Record<string, unknown> | null> {',
    '  const coords = resolveHookCoords()',
    '  const paneKey = process.env.ORCA_PANE_KEY',
    '  const launchToken = process.env.ORCA_AGENT_LAUNCH_TOKEN',
    '  if (!coords.port || !coords.token || !paneKey || !launchToken) return null',
    '  const controller = typeof AbortController !== "undefined" ? new AbortController() : null',
    '  const timeout = setTimeout(() => controller?.abort(), COLLABORATION_TOOL_CHECKPOINT_TIMEOUT_MS)',
    "  if (typeof timeout.unref === 'function') timeout.unref()",
    '  try {',
    '    const response = await fetch(`http://127.0.0.1:${coords.port}${path}`, {',
    "      method: 'POST',",
    '      headers: {',
    "        'Content-Type': 'application/json',",
    "        'X-Orca-Agent-Hook-Token': coords.token,",
    '      },',
    '      body: JSON.stringify({ paneKey, launchToken, ...payload }),',
    '      ...(controller ? { signal: controller.signal } : {}),',
    '    })',
    '    if (!response.ok) return null',
    '    const parsed = await response.json()',
    "    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed as Record<string, unknown> : null",
    '  } catch {',
    '    return null',
    '  } finally {',
    '    clearTimeout(timeout)',
    '  }',
    '}',
    '',
    'function parsePreparedCollaborationEntries(value: unknown): Array<{ deliveryId: string; deliveryAttempt: number; message: Record<string, unknown> }> {',
    '  if (!Array.isArray(value)) return []',
    '  const entries: Array<{ deliveryId: string; deliveryAttempt: number; message: Record<string, unknown> }> = []',
    '  for (const candidate of value) {',
    "    if (!candidate || typeof candidate !== 'object' || Array.isArray(candidate)) return []",
    '    const record = candidate as Record<string, unknown>',
    '    const message = record.message',
    '    if (',
    "      typeof record.deliveryId !== 'string' ||",
    '      !Number.isInteger(record.deliveryAttempt) ||',
    '      (record.deliveryAttempt as number) < 1 ||',
    "      !message || typeof message !== 'object' || Array.isArray(message)",
    '    ) return []',
    '    entries.push({',
    '      deliveryId: record.deliveryId,',
    '      deliveryAttempt: record.deliveryAttempt as number,',
    '      message: message as Record<string, unknown>,',
    '    })',
    '  }',
    '  return entries',
    '}',
    '',
    'function formatCollaborationToolContextPatch(entries: Array<{ deliveryId: string; deliveryAttempt: number; message: Record<string, unknown> }>): string {',
    "  const sections = ['=== COLLABORATION CONTEXT PATCH ===']",
    '  for (const entry of entries) {',
    '    const message = entry.message',
    "    const topic = typeof message.topic === 'string' ? message.topic : ''",
    "    const type = typeof message.type === 'string' ? message.type : ''",
    "    const priority = typeof message.priority === 'string' ? message.priority : ''",
    "    const producerKey = typeof message.producerKey === 'string' ? message.producerKey : ''",
    "    const body = typeof message.body === 'string' ? message.body : ''",
    '    sections.push(`delivery ${entry.deliveryId} attempt=${entry.deliveryAttempt}`)',
    '    sections.push(`${topic} ${type} ${priority} producer=${producerKey}`.trim())',
    '    sections.push(body)',
    '  }',
    '  return sections.join("\\n")',
    '}',
    '',
    'function isExplicitCollaborationStageCheckpointToolResult(event: unknown): boolean {',
    "  if (!event || typeof event !== 'object') return false",
    '  const record = event as { toolName?: unknown; input?: unknown }',
    "  if (record.toolName !== 'bash' || !record.input || typeof record.input !== 'object' || Array.isArray(record.input)) return false",
    '  const command = (record.input as { command?: unknown }).command',
    "  if (typeof command !== 'string') return false",
    '  return /(?:^|[\\s;&|])(?:[^\\s;&|]*[/])?orca(?:-dev|-ide)?\\s+collaboration\\s+checkpoint(?:-ack)?(?:\\s|$)/u.test(command)',
    '}',
    '',
    'async function prepareCollaborationToolResult(event: unknown): Promise<Record<string, unknown> | undefined> {',
    '  if (pendingCollaborationCheckpointAcks.length > 0 || armedCollaborationCheckpointAcks.length > 0 || collaborationToolCheckpointPrepareInFlight) return undefined',
    "  if (!event || typeof event !== 'object') return undefined",
    '  if (isExplicitCollaborationStageCheckpointToolResult(event)) return undefined',
    '  collaborationToolCheckpointPrepareInFlight = true',
    '  try {',
    `    const result = await callCollaborationToolCheckpoint(${JSON.stringify(COLLABORATION_TOOL_CHECKPOINT_PREPARE_PATH)}, {})`,
    '    if (result?.active !== true) return undefined',
    '    const entries = parsePreparedCollaborationEntries(result.entries)',
    '    if (entries.length === 0) return undefined',
    '    const content = (event as { content?: unknown }).content',
    '    if (!Array.isArray(content)) return undefined',
    '    pendingCollaborationCheckpointAcks = entries.map(({ deliveryId, deliveryAttempt }) => ({ deliveryId, deliveryAttempt }))',
    '    return {',
    '      content: [',
    '        ...content,',
    "        { type: 'text', text: formatCollaborationToolContextPatch(entries) },",
    '      ],',
    '    }',
    '  } finally {',
    '    collaborationToolCheckpointPrepareInFlight = false',
    '  }',
    '}',
    '',
    'function providerPayloadContainsCollaborationDelivery(payload: unknown, deliveryId: string, deliveryAttempt: number): boolean {',
    '  let serialized: string',
    '  try {',
    '    serialized = JSON.stringify(payload)',
    '  } catch {',
    '    return false',
    '  }',
    "  if (typeof serialized !== 'string') return false",
    "  return serialized.includes('=== COLLABORATION CONTEXT PATCH ===') && serialized.includes(`delivery ${deliveryId} attempt=${deliveryAttempt}`)",
    '}',
    '',
    'function armCollaborationToolContextForProviderRequest(event: unknown): void {',
    '  if (pendingCollaborationCheckpointAcks.length === 0 && armedCollaborationCheckpointAcks.length === 0) return',
    "  const payload = event && typeof event === 'object' && !Array.isArray(event) ? (event as { payload?: unknown }).payload : undefined",
    '  const candidates = [...armedCollaborationCheckpointAcks, ...pendingCollaborationCheckpointAcks]',
    '  const seen = new Set<string>()',
    '  armedCollaborationCheckpointAcks = candidates.filter((entry) => {',
    '    const key = `${entry.deliveryId}:${entry.deliveryAttempt}`',
    '    if (seen.has(key)) return false',
    '    seen.add(key)',
    '    return providerPayloadContainsCollaborationDelivery(payload, entry.deliveryId, entry.deliveryAttempt)',
    '  })',
    '  pendingCollaborationCheckpointAcks = []',
    '}',
    '',
    'async function acknowledgeArmedCollaborationToolContext(event: unknown): Promise<void> {',
    "  const role = event && typeof event === 'object' && !Array.isArray(event) ? (event as { message?: { role?: unknown } }).message?.role : undefined",
    "  if (role !== 'assistant' || armedCollaborationCheckpointAcks.length === 0) return",
    '  const snapshot = armedCollaborationCheckpointAcks.map((entry) => ({ ...entry }))',
    `  const result = await callCollaborationToolCheckpoint(${JSON.stringify(COLLABORATION_TOOL_CHECKPOINT_ACK_PATH)}, { acknowledgements: snapshot })`,
    '  if (!result || result.active === false) return',
    '  const settledIds = new Set<string>()',
    '  for (const key of ["ackedDeliveryIds", "ignoredDeliveryIds"] as const) {',
    '    const values = result[key]',
    '    if (!Array.isArray(values)) continue',
    "    for (const value of values) if (typeof value === 'string') settledIds.add(value)",
    '  }',
    '  if (settledIds.size === 0) return',
    '  const settledSnapshotKeys = new Set(snapshot.filter(({ deliveryId }) => settledIds.has(deliveryId)).map(({ deliveryId, deliveryAttempt }) => `${deliveryId}:${deliveryAttempt}`))',
    '  armedCollaborationCheckpointAcks = armedCollaborationCheckpointAcks.filter(({ deliveryId, deliveryAttempt }) => !settledSnapshotKeys.has(`${deliveryId}:${deliveryAttempt}`))',
    '}',
    ''
  ]
}

export function getPiCollaborationToolCheckpointHandlerSourceLines(kind: PiAgentKind): string[] {
  if (kind !== 'pi') {
    return []
  }
  return [
    "  pi.on('tool_result', async (event) => {",
    '    return await prepareCollaborationToolResult(event)',
    '  })',
    '',
    "  // Why: Pi exposes no observer after all before_provider_request payload rewriters; this verifies the payload at Orca's position in the trusted extension chain. A later third-party rewriter can still remove it; message_start only proves the provider accepted a request emitted after this observer.",
    "  pi.on('before_provider_request', (event) => {",
    '    armCollaborationToolContextForProviderRequest(event)',
    '  })',
    '',
    "  pi.on('message_start', async (event) => {",
    '    await acknowledgeArmedCollaborationToolContext(event)',
    '  })',
    ''
  ]
}
