// Compatibility seam verified against OMP 18.0.10: the active composer is
// exposed through TUI getFocused(), has the checked fields below, and is
// submit-ready only after disableSubmit becomes false. The native idle title
// can arrive earlier, so unsupported or incomplete shapes must fail closed.
// OMP emits input.text after its editor normalizer (CRLF -> LF, NFC, tab
// expansion, control removal, trim). Hash that emitted text verbatim; the host
// mirrors those known stages for its expected fingerprint. Do not guess about
// later image/emoji transforms: the exact before_agent_start prompt match
// fails closed if they changed the text. Its keyboard-CSI decoder is inert for
// injected prompts because Orca replaces ESC before PTY delivery.
export function getOmpPromptReadinessSourceLines(): string[] {
  return [
    'function installOmpPromptReadiness(pi) {',
    "  const markerPrefix = '\\x1b]777;orca-omp-prompt;'",
    "  const markerSuffix = '\\x07'",
    "  const widgetKey = 'orca-omp-prompt-readiness'",
    "  const sharedKey = '__orcaOmpPromptReadiness'",
    "  const shared = globalThis[sharedKey] || (globalThis[sharedKey] = { state: 'unknown', sessionEpoch: 0, largePasteConfigured: false, requestRender: null })",
    '  let disposeActive = () => {}',
    '  if (!shared.largePasteSetup) {',
    "    shared.largePasteSetup = import('@oh-my-pi/pi-coding-agent')",
    '      .then((module) => {',
    '        try {',
    '          const settings = module?.Settings?.instance',
    "          if (!settings || typeof settings.override !== 'function') return false",
    "          settings.override('paste.largeMenuThreshold', 0)",
    '          return true',
    '        } catch {',
    '          return false',
    '        }',
    '      })',
    '      .catch(() => false)',
    '      .then((configured) => {',
    '        shared.largePasteConfigured = configured === true',
    '        try { shared.requestRender?.() } catch {}',
    '        return shared.largePasteConfigured',
    '      })',
    '  }',
    '',
    '  function emit(next) {',
    '    if (shared.state === next) return',
    '    shared.state = next',
    '    try {',
    '      process.stdout?.write?.(markerPrefix + next + markerSuffix)',
    '    } catch {}',
    '  }',
    '',
    '  function isComposer(candidate) {',
    "    if (!candidate || typeof candidate !== 'object') return false",
    '    return Array.isArray(candidate.pendingImages)',
    '      && Array.isArray(candidate.pendingImageLinks)',
    "      && typeof candidate.getExpandedText === 'function'",
    "      && typeof candidate.getText === 'function'",
    "      && typeof candidate.clearDraft === 'function'",
    "      && typeof candidate.disableSubmit === 'boolean'",
    '  }',
    '',
    '  shared.sessionEpoch += 1',
    '  let activeEpoch = shared.sessionEpoch',
    '  let pendingInteractiveInput = null',
    "  emit('blocked')",
    "  pi.on('input', (event) => {",
    "    if (event?.source !== 'interactive' || typeof event.text !== 'string') return",
    '    if (activeEpoch === 0 || shared.sessionEpoch !== activeEpoch) return',
    '    pendingInteractiveInput = { epoch: activeEpoch, text: event.text }',
    "    emit('blocked')",
    '  })',
    "  pi.on('before_agent_start', async (event) => {",
    '    const pending = pendingInteractiveInput',
    '    pendingInteractiveInput = null',
    '    if (!pending || event?.prompt !== pending.text) return',
    '    if (activeEpoch === 0 || pending.epoch !== activeEpoch || shared.sessionEpoch !== activeEpoch) return',
    '    try {',
    '      const subtle = globalThis.crypto?.subtle',
    "      if (!subtle || typeof TextEncoder !== 'function') return",
    "      const digest = await subtle.digest('SHA-256', new TextEncoder().encode(pending.text))",
    '      if (activeEpoch === 0 || pending.epoch !== activeEpoch || shared.sessionEpoch !== activeEpoch) return',
    "      const hash = Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('')",
    "      emit('blocked')",
    "      process.stdout?.write?.(markerPrefix + 'submitted;' + hash + markerSuffix)",
    '    } catch {}',
    '  })',
    "  pi.on('session_start', (_event, ctx) => {",
    '    const epoch = ++shared.sessionEpoch',
    '    activeEpoch = epoch',
    '    pendingInteractiveInput = null',
    '    disposeActive()',
    "    emit('blocked')",
    '    if (ctx?.hasUI === false) return',
    '    let disposed = false',
    '    let timer = null',
    '    let timerGeneration = 0',
    '    let composer = null',
    '    let requestRender = null',
    '',
    '    function cancelTimer() {',
    '      timerGeneration += 1',
    '      if (timer !== null) {',
    '        try { clearTimeout(timer) } catch {}',
    '        timer = null',
    '      }',
    '    }',
    '',
    '    function getComposer(tui) {',
    '      try {',
    "        if (!tui || typeof tui.getFocused !== 'function') return null",
    '        if (!Array.isArray(tui.overlayStack) || tui.overlayStack.length !== 0) return null',
    '        const focused = tui.getFocused()',
    '        return isComposer(focused) ? focused : null',
    '      } catch {',
    '        return null',
    '      }',
    '    }',
    '',
    '    function isReady(tui) {',
    '      if (shared.largePasteConfigured !== true) return false',
    '      const focused = getComposer(tui)',
    '      if (!focused) return false',
    '      if (composer === null) composer = focused',
    '      if (focused !== composer) return false',
    '      try {',
    "        return !!ctx && typeof ctx.isIdle === 'function' && ctx.isIdle() && focused.disableSubmit === false",
    '      } catch {',
    '        return false',
    '      }',
    '    }',
    '',
    '    function createSentinel(tui) {',
    '      requestRender = () => {',
    '        if (disposed || shared.sessionEpoch !== epoch) return',
    '        try { tui?.requestRender?.() } catch {}',
    '      }',
    '      shared.requestRender = requestRender',
    '      function evaluate() {',
    '        if (disposed || shared.sessionEpoch !== epoch) return',
    '        if (!isReady(tui)) {',
    '          cancelTimer()',
    "          emit('blocked')",
    '          return',
    '        }',
    "        if (shared.state === 'ready' || timer !== null) return",
    '        const generation = ++timerGeneration',
    '        try {',
    '          timer = setTimeout(() => {',
    '            if (disposed || shared.sessionEpoch !== epoch || generation !== timerGeneration) return',
    '            timer = null',
    '            if (isReady(tui)) {',
    "              if (shared.state !== 'ready') pendingInteractiveInput = null",
    "              emit('ready')",
    '            } else {',
    "              emit('blocked')",
    '            }',
    '          }, 0)',
    '          timer?.unref?.()',
    '        } catch {',
    "          emit('blocked')",
    '        }',
    '      }',
    '',
    '      return {',
    '        invalidate() {},',
    '        render() {',
    '          evaluate()',
    '          return []',
    '        },',
    '        dispose() {',
    '          dispose()',
    '        }',
    '      }',
    '    }',
    '',
    '    function dispose() {',
    '      if (disposed) return false',
    '      disposed = true',
    '      cancelTimer()',
    '      const active = shared.sessionEpoch === epoch',
    '      if (shared.requestRender === requestRender) shared.requestRender = null',
    "      if (active) emit('blocked')",
    '      return active',
    '    }',
    '',
    '    disposeActive = () => {',
    '      return dispose()',
    '    }',
    '    try {',
    "      if (!ctx?.ui || typeof ctx.ui.setWidget !== 'function') return",
    "      ctx.ui.setWidget(widgetKey, createSentinel, { placement: 'belowEditor' })",
    '    } catch {',
    "      emit('blocked')",
    '    }',
    '  })',
    "  pi.on('session_shutdown', (_event, ctx) => {",
    '    const active = disposeActive()',
    '    if (!active) return',
    '    activeEpoch = 0',
    '    pendingInteractiveInput = null',
    '    shared.requestRender = null',
    '    try { ctx?.ui?.setWidget?.(widgetKey, undefined) } catch {}',
    '  })',
    '}',
    ''
  ]
}

/**
 * A deliberately narrow OMP extension for terminals where status hooks are
 * disabled. It retains the ownership check used by the full status extension,
 * but only installs the composer-readiness sentinel: no hook callbacks, HTTP
 * posting, or status reconciliation are loaded into the worker.
 */
export function getOmpPromptReadinessExtensionSource(): string {
  return [
    ...getOmpPromptReadinessSourceLines(),
    'export default function (pi) {',
    '  const ownerPid = process.env.ORCA_PI_STATUS_OWNED',
    '  const selfPid = String(process.pid)',
    '  if (ownerPid && ownerPid !== selfPid) return',
    '  process.env.ORCA_PI_STATUS_OWNED = selfPid',
    '  if (process.env.ORCA_PANE_KEY) installOmpPromptReadiness(pi)',
    '}',
    ''
  ].join('\n')
}
